// Code generated by goagen v1.4.1, DO NOT EDIT.
//
// API "adder": Application User Types
//
// Command:
// $ goagen
// --design=github.com/youyouryu/goa-tutorial/design
// --out=/Users/yuyamada/Documents/Programing/goa-tutorial
// --version=v1.4.1

package app
